[package]
name = "advent-of-code-day1"
version = "0.1.0"
edition = "2021"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
